{"uuid": "018b0762-938e-4e72-850f-2dbffe5f41ef", "children": ["b0846196-b8de-415a-83f6-d8138bfad14a", "58faa513-70d6-4693-b60a-f04684203173"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78\n\n", "trace": "  File \"D:\\Python3.7\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python3.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python3.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Python3.7\\lib\\site-packages\\_pytest\\python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\Python3.7\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\Projects\\webTest\\yidaCloud\\testCase\\test_newFenqi.py\", line 20, in setup_class\n    self.driver = BrowserEngine().init_browser()  #打开浏览器\n  File \"D:\\Projects\\webTest\\yidaCloud\\baseClass\\browserEngine.py\", line 27, in init_browser\n    self._driver = webdriver.Chrome(executable_path=self.CHROME)\n  File \"D:\\Python3.7\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"D:\\Python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595922480642, "stop": 1595922490324}], "start": 1595922480642, "stop": 1595922490564}